# Generated by Django 4.2.7 on 2026-02-02 06:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='crm_restaur_created_76cc8f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('total_spend_cents', models.BigIntegerField(default=0)),
                ('last_visit_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='crm.restaurant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('segment_type', models.CharField(choices=[('inactive_days', 'Inactive Days'), ('high_spenders', 'High Spenders')], max_length=20)),
                ('segment_value', models.IntegerField(help_text='Days for inactive_days, cents for high_spenders')),
                ('message_template', models.TextField(help_text='Supports {first_name} placeholder')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='crm.restaurant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('spend_cents', models.BigIntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='crm.customer')),
            ],
            options={
                'ordering': ['-visited_at'],
                'indexes': [models.Index(fields=['visited_at'], name='crm_visit_visited_43c90c_idx'), models.Index(fields=['customer', 'visited_at'], name='crm_visit_custome_8b4cc7_idx')],
            },
        ),
        migrations.CreateModel(
            name='OutreachEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email')], default='email', max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='queued', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreach_events', to='crm.campaign')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreach_events', to='crm.customer')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='crm_outreac_status_2606ca_idx'), models.Index(fields=['campaign', 'status'], name='crm_outreac_campaig_841a92_idx'), models.Index(fields=['created_at'], name='crm_outreac_created_87ea6b_idx')],
                'unique_together': {('campaign', 'customer')},
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['last_visit_at'], name='crm_custome_last_vi_2083f9_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['total_spend_cents'], name='crm_custome_total_s_552490_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['restaurant', 'email'], name='crm_custome_restaur_c53a0d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('restaurant', 'email')},
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status'], name='crm_campaig_status_650d2a_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['restaurant', 'status'], name='crm_campaig_restaur_fd5d56_idx'),
        ),
    ]
